// Measures every sprite in client/img and writes shared/sprite-sizes.js.
//
// The art is drawn with one pen: an outline 8 source pixels thick. Drawing
// every sprite at PX world units per source pixel therefore gives every
// object the same outline on screen, and the size table below turns each
// sprite's solid silhouette into its hitbox. Run after adding or changing art:
//
//   node tools/measure-sprites.mjs

import { readdirSync, writeFileSync } from 'node:fs';
import { readPng } from './png.js';
import { measureSprite } from '../shared/measure.js';

const root = new URL('../client/img/', import.meta.url).pathname;
const out = new URL('../shared/sprite-sizes.js', import.meta.url).pathname;
const DIRS = ['world', 'items', 'animals', 'hats', 'weapons'];

const rows = [];
for (const dir of DIRS) {
  for (const f of readdirSync(root + dir).filter((n) => n.endsWith('.png')).sort()) {
    if (f.includes('_shadow')) continue;
    const m = measureSprite(readPng(root + dir + '/' + f));
    if (!m) throw new Error(`${dir}/${f} has no solid pixels`);
    rows.push([`${dir}/${f.slice(0, -4)}`, m]);
  }
}

const lines = rows.map(([key, m]) => `  '${key}': { w: ${m.width}, h: ${m.height}, outline: ${m.outline}, r: ${m.radius}, cx: ${m.cx}, cy: ${m.cy}, inner: ${m.inner}${m.alpha ? `, alpha: ${m.alpha}` : ''} },`);
writeFileSync(out, `// Generated by tools/measure-sprites.mjs — do not edit by hand.
//
// Every sprite's size in source pixels, its outer outline thickness, and the
// radius of a circle with the same area as its solid silhouette (the halo is
// not counted). See shared/sprites.js for how these become world sizes.

export const MEASURED = {
${lines.join('\n')}
};
`);
console.log(`measured ${rows.length} sprites → shared/sprite-sizes.js`);
