// The arcade's catalogue. One entry per game: `dir`, `port` and `health` are
// what the launcher needs; everything else is what the game's page, its tile,
// the sitemap and the search engines see. Adding a game means adding an entry
// here, a 16:9 image in public/art/, and a proxy block in the Nginx config.
//
// `updated` is the date the game last changed in a way a player would notice.
// It is shown on the game's page and sent to search engines, so bump it with
// the change rather than on every deploy.

import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

export const games = {
  sideways: {
    name: 'Sideways',
    dir: path.join(root, 'sideways'),
    port: 3207,
    health: '/health',
    headline: 'Car Drifting Game',
    description: 'Drift through a night city in your browser: street drifting, takeovers with donuts, rollbacks and flames, and a judged drift circuit. Free, no download.',
    about: [
      'Sideways is a 3D car drifting game that runs in your browser. One night city holds three kinds of driving: chaining slides through the downtown streets, running a street takeover in the Pit, and putting down judged laps on the harbour circuit.',
      'The car is easy to throw sideways on a keyboard. Driver aids hold the angle for you, and you can turn them down or off once you want all of the control. There are three cars, a turbo straight-six coupe, a supercharged V8 and a rotary, each with its own engine sound, rev limiter and flames.',
    ],
    modes: [
      ['Downtown', 'Chain drifts through the streets. Sliding close to walls scores more, and hitting something loses the combo.'],
      ['The Pit', 'A two-and-a-half-minute takeover. Donuts, figure eights, rollbacks, burnouts and limiter flames build the crowd’s hype, which multiplies your score, until the police arrive.'],
      ['Harbor Circuit', 'A 2 km walled track with clipping points and outer zones. Every lap is scored for line, angle and style.'],
    ],
    tips: [
      'To drift, tap Space as you turn in and hold W. Steer into the corner for more angle and out of it to straighten up.',
      'For a rollback, hold Space and a direction at speed until you are past sideways, then let go of Space and keep holding the direction and W.',
      'Hold W and S together from a stop for a burnout, or F and W for the two-step.',
    ],
    controls: [
      ['W / ↑', 'Throttle'],
      ['S / ↓', 'Brake, hold to reverse'],
      ['A / D', 'Steer'],
      ['Space', 'Handbrake'],
      ['Shift', 'Clutch, tap it for a clutch kick'],
      ['F', 'Two-step'],
      ['E / Q', 'Shift up / down (manual gearbox)'],
      ['C', 'Camera'],
      ['R', 'Reset the car'],
    ],
    devices: 'Keyboard, gamepad or touch',
    players: 'Single player',
    playMode: 'SinglePlayer',
    genre: ['Racing', 'Driving', 'Simulation'],
    tags: ['racing', 'drifting', '3d', 'solo'],
    art: '/assets/art/sideways.jpg',
    published: '2026-09-29',
    updated: '2026-09-29',
    fresh: true,
  },

  mootopia: {
    name: 'Mootopia',
    dir: path.join(root, 'mootopia'),
    port: 3206,
    health: '/health',
    headline: 'Gather, Build and Fight .io Game',
    description: 'Chop trees, mine gold, age up and build a windmill village, then defend it from other players, wolves and a boss bear. A free multiplayer .io game.',
    about: [
      'Mootopia is a top-down multiplayer .io game in the classic style. You gather wood, food, stone and gold, age up, and pick an upgrade at every age from 2 to 9: sixteen weapons and twenty-three buildings, from walls and spikes to windmills, turrets and teleporters.',
      'The map has snow in the north, desert in the south and a river with a current through the middle. Join a clan, buy hats that each change how you play, and keep an eye out for the boss bear. Bots keep a quiet server busy and step aside as people join.',
    ],
    modes: [
      ['Gather', 'Every tree, bush, rock and gold vein can be harvested. Windmills and mines earn for you while you do something else.'],
      ['Build', 'Walls, spikes, traps, boost pads, turrets and spawn pads. Weapons earn gold, diamond and ruby finishes the more you use them.'],
      ['Fight', 'Other players, wolves, boars, tuskers and a boss bear. Clans share a minimap and can ping each other.'],
    ],
    controls: [
      ['W A S D / arrows', 'Move'],
      ['Mouse', 'Aim'],
      ['Click / Space', 'Hit, or place what you are holding'],
      ['1 – 9', 'Pick a tool or item'],
      ['Q', 'Eat'],
      ['F / V', 'Trap or pad / spikes'],
      ['E', 'Auto-hit'],
      ['X', 'Lock aim'],
      ['R', 'Ping your clan'],
      ['Enter', 'Chat'],
    ],
    devices: 'Keyboard and mouse',
    players: 'Online multiplayer',
    playMode: 'MultiPlayer',
    genre: ['Strategy', 'Action', 'MMO'],
    tags: ['io', 'building', 'pvp', 'multiplayer'],
    art: '/assets/art/mootopia.jpg',
    published: '2026-09-28',
    updated: '2026-09-29',
  },

  stormwall: {
    name: 'Stormwall',
    dir: path.join(root, 'stormwall'),
    port: 3205,
    health: '/health',
    headline: '100-Player Build Battle Royale',
    description: 'Drop from the blimp, harvest, build walls and ramps, and be the last one standing as the storm closes in. A free 100-player battle royale in your browser.',
    about: [
      'Stormwall is a 100-player build-and-shoot battle royale in your browser. Drop onto the island, harvest everything you can reach, throw up walls and ramps in a heartbeat and outlast the storm. Play solo, in duos or in squads; bots fill every empty seat.',
      'Anything on the island can be broken down for wood, brick or metal. Builds start weak and gain health over a few seconds, and you can edit your own pieces into doors, windows and stairs. Matches earn XP, coins and daily challenge progress, which unlock outfits, gliders and pickaxes. None of them change how you play.',
    ],
    modes: [
      ['Solo, duos and squads', 'A minute on the pre-game island, then the blimp. In teams you get knocked down instead of eliminated, and a teammate can revive you.'],
      ['Practice', 'A sandbox with a full kit and materials for trying out builds.'],
    ],
    controls: [
      ['W A S D', 'Move'],
      ['Shift / Space / C', 'Sprint / jump / crouch'],
      ['Mouse', 'Aim (right button) and fire (left button)'],
      ['1 – 6 / wheel', 'Pickaxe and weapon slots'],
      ['Q / F / Z / X', 'Build a wall / floor / ramp / cone'],
      ['G', 'Edit one of your builds'],
      ['E', 'Pick up, open chests, revive'],
      ['R', 'Reload'],
      ['M / Tab', 'Map / scores'],
    ],
    devices: 'Keyboard and mouse',
    players: 'Up to 100 players',
    playMode: 'MultiPlayer',
    genre: ['Shooter', 'Battle royale', 'Action'],
    tags: ['battle royale', 'building', 'shooter', 'multiplayer'],
    art: '/assets/art/stormwall.jpg',
    published: '2026-09-27',
    updated: '2026-09-27',
  },

  glowworm: {
    name: 'Glowworm',
    dir: path.join(root, 'glowworm'),
    port: 3204,
    health: '/health',
    headline: 'Multiplayer Neon Snake Game',
    description: 'Eat glowing pellets, cut other worms off and grow as long as you can. A free multiplayer snake .io game for desktop and mobile.',
    about: [
      'Glowworm is a multiplayer snake game. Eat the glowing pellets to grow, then cut across other worms so their heads run into your body, and eat what they leave behind.',
      'Your own body never kills you, but everyone else’s does, and so does the red edge of the arena. When two heads meet, the smaller worm dies. Boosting makes you faster but costs length and drops it behind you as food, so a boosting worm is worth chasing. Around thirty bots keep the arena busy and step aside as people join.',
    ],
    controls: [
      ['Mouse / ← → / A D', 'Steer'],
      ['Mouse button / Space / W', 'Boost'],
      ['Phone: drag anywhere', 'Steer with the joystick under your thumb'],
      ['Phone: ⚡ or a second finger', 'Boost'],
    ],
    devices: 'Mouse, keyboard or touch',
    players: 'Online multiplayer',
    playMode: 'MultiPlayer',
    genre: ['Arcade', 'Action'],
    tags: ['multiplayer', 'io', 'snake'],
    art: '/assets/art/glowworm.jpg',
    published: '2026-09-21',
    updated: '2026-09-21',
  },

  duostrike: {
    name: 'DuoStrike',
    dir: path.join(root, 'duostrike'),
    port: 3201,
    health: '/health',
    headline: 'Two-Player Co-op Shooter',
    description: 'Team up with one friend for a co-op campaign of gunfights, sword fights, parkour and puzzles that need both of you. Free in your browser, no download.',
    about: [
      'DuoStrike is a co-op shooter for exactly two players. One of you creates a room and shares the four-letter code, the other joins, and you play through the campaign together.',
      'Every level has something one player cannot finish alone: two switches to throw within three seconds of each other, a generator to hold while the other runs for the relay, a core to carry while your partner covers you. Between fights you are back in the village to buy colours and get a hint.',
    ],
    modes: [
      ['Campaign', 'Training grounds, a gunfight arena, a sword corridor, a parkour gauntlet, zombie waves and a finale, with the village hub in between.'],
      ['Movement', 'Sprint, slide under bars, wall-jump up shafts. The rifle, shotgun and sword each have their place.'],
    ],
    controls: [
      ['W A S D', 'Move'],
      ['Mouse', 'Look'],
      ['Shift / Ctrl', 'Sprint / slide'],
      ['Space', 'Jump, or jump off a wall'],
      ['C', 'Crouch'],
      ['Left / right click', 'Fire / aim or block'],
      ['1 2 3', 'Rifle, shotgun, sword'],
      ['R', 'Reload'],
      ['E', 'Interact'],
    ],
    devices: 'Keyboard and mouse',
    players: '2 players, co-op',
    playMode: 'CoOp',
    genre: ['Shooter', 'Adventure', 'Action'],
    tags: ['co-op', 'shooter', 'multiplayer'],
    art: '/assets/art/duostrike.jpg',
    published: '2026-07-26',
    updated: '2026-09-02',
  },

  'pixel-brawl': {
    name: 'Pixel Brawl',
    dir: path.join(root, 'pixel brawl'),
    port: 3202,
    health: '/api/status',
    headline: 'Pixel Arena Brawler',
    description: 'A pixel-art arena brawler with Gem Grab, Showdown, Bounty and Duels against bots or players. Unlock and upgrade 18 brawlers. Free on phone or desktop.',
    about: [
      'Pixel Brawl is a pixel-art arena brawler with four modes. Queue against bots for an instant match or against players, with bots topping up the lobby when it is quiet. Parties of up to four stay on the same team.',
      'There are eighteen brawlers across six rarities. Boxes give cards, coins, gems and new brawlers, and trophies climb per brawler along a trophy road.',
    ],
    modes: [
      ['Gem Grab (3v3)', 'Hold ten gems through a fifteen-second countdown. Dying drops your gems.'],
      ['Showdown (8 players)', 'Last brawler standing. Crates drop power cubes while the poison closes in.'],
      ['Bounty (2v2)', 'Knockouts earn the other brawler’s stars. Most stars at the end wins.'],
      ['Duel (1v1)', 'Three lives each.'],
    ],
    controls: [
      ['W A S D', 'Move'],
      ['Mouse / left click', 'Aim / shoot'],
      ['Right click / Shift', 'Super'],
      ['Phone: left side', 'Move stick'],
      ['Phone: attack button', 'Drag to aim and release to fire, or tap to auto-aim'],
    ],
    devices: 'Phone or desktop',
    players: 'Single player or online',
    playMode: 'MultiPlayer',
    genre: ['Action', 'Arcade'],
    tags: ['brawler', 'pixel', 'multiplayer', 'solo'],
    art: '/assets/art/pixel-brawl.jpg',
    published: '2026-07-26',
    updated: '2026-09-02',
  },

  'circuit-breaker': {
    name: 'Circuit Breaker',
    dir: path.join(root, 'circuit-breaker'),
    port: 3203,
    health: '/health',
    headline: 'Neon Tower Defence Game',
    description: 'Build a maze of towers that overheat and stop the packets before they reach your core. 25 waves, 5 towers and 3 bosses. Free tower defence in your browser.',
    about: [
      'Circuit Breaker is a tower defence game on a neon circuit board. Packets enter on the left and walk to your core on the right. You cannot wall the route off, only bend it, so the first half of the game is making that walk as long as you can.',
      'The second half is heat. Every tower warms up as it fires and shuts down at its limit until it cools off. Overclock doubles a tower’s rate of fire for five seconds and ignores the limit, with a guaranteed shutdown straight after. Saving it for the right moment of a boss wave is most of the skill.',
    ],
    modes: [
      ['Pulse Node', 'Cheap, fast and cool-running. Falls off against armour.'],
      ['Cryo Vent', 'Slows a small area. Almost no damage, never overheats.'],
      ['Arc Relay', 'Chains between three packets.'],
      ['Rail Cannon', 'Slow and splashing, the answer to armour. Runs hot.'],
      ['Laser Grid', 'Ramps up the longer it holds a target. Runs hottest.'],
    ],
    modesTitle: 'Towers',
    controls: [
      ['Click a card, then a cell', 'Build'],
      ['Click a tower', 'Upgrade, overclock or sell it'],
      ['1 – 5', 'Pick a tower'],
      ['Space', 'Send the next wave early for a bonus'],
      ['Q', 'Surge: damage and stun everything'],
      ['Esc', 'Cancel'],
    ],
    devices: 'Mouse or touch',
    players: 'Single player',
    playMode: 'SinglePlayer',
    genre: ['Strategy', 'Tower defense'],
    tags: ['strategy', 'tower defence', 'solo'],
    art: '/assets/art/circuit-breaker.jpg',
    published: '2026-09-06',
    updated: '2026-09-06',
  },
};

// Runtime state the launcher keeps next to each entry.
for (const game of Object.values(games)) Object.assign(game, { state: 'stopped', process: null, sessions: new Map(), lastActivity: 0, startPromise: null });
